filter:
    excluded_paths:
        - vendor/*
        - config/*
        - test/*

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build:
    environment:
        variables:
            XDEBUG_MODE: coverage
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
